In [2]:
import pandas as pd
pd.__version__

'3.0.5'

In [3]:
url = "https://raw.githubusercontent.com/byuidatascience/data4python4ds/master/data-raw/flights/flights.csv"
flights = pd.read_csv(url)

In [5]:
flights.info()

<class 'pandas.DataFrame'>
RangeIndex: 336776 entries, 0 to 336775
Data columns (total 19 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   year            336776 non-null  int64
 1   month           336776 non-null  int64
 2   day             336776 non-null  int64
 3   dep_time        328521 non-null  float64
 4   sched_dep_time  336776 non-null  int64
 5   dep_delay       328521 non-null  float64
 6   arr_time        328063 non-null  float64
 7   sched_arr_time  336776 non-null  int64
 8   arr_delay       327346 non-null  float64
 9   carrier         336776 non-null  str
 10  flight          336776 non-null  int64
 11  tailnum         334264 non-null  str
 12  origin          336776 non-null  str
 13  dest            336776 non-null  str
 14  air_time        327346 non-null  float64
 15  distance        336776 non-null  int64
 16  hour            336776 non-null  int64
 17  minute          336776 non-null  int64
 18  time_hour       336776 non-null  str
dtypes: float64(5), int64(9), str(5)
memory usage: 59.8 MB

![](https://pandas.pydata.org/docs/_images/01_table_dataframe.svg)

In [6]:
df = pd.DataFrame(
    data={
        "col0": [0, 0, 0, 0],
        "col1": [0, 0, 0, 0],
        "col2": [0, 0, 0, 0],
        "col3": ["a", "b", "b", "a"],
        "col4": ["alpha", "gamma", "gamma", "gamma"],
    },
    index=["row" + str(i) for i in range(4)],
)
df.head()

      col0  col1  col2 col3   col4
row0     0     0     0    a  alpha
row1     0     0     0    b  gamma
row2     0     0     0    b  gamma
row3     0     0     0    a  gamma

In [7]:
(
    flights
    .query("dest == 'IAH'")
    .groupby(["year", "month", "day"])[["arr_delay"]]
    .mean()
)

                arr_delay
year month day
2013 1     1    17.850000
           2     7.000000
           3    18.315789
           4    -3.200000
           5    20.230769
...                   ...
     12    27    6.166667
           28    9.500000
           29   23.611111
           30   23.684211
           31   -4.933333

[365 rows x 1 columns]

In [8]:
flights["time_hour"]

0         2013-01-01T10:00:00Z
1         2013-01-01T10:00:00Z
2         2013-01-01T10:00:00Z
3         2013-01-01T10:00:00Z
4         2013-01-01T11:00:00Z
                  ...
336771    2013-09-30T18:00:00Z
336772    2013-10-01T02:00:00Z
336773    2013-09-30T16:00:00Z
336774    2013-09-30T15:00:00Z
336775    2013-09-30T12:00:00Z
Name: time_hour, Length: 336776, dtype: str

In [9]:
flights["time_hour"] = pd.to_datetime(flights["time_hour"], format="%Y-%m-%dT%H:%M:%SZ")

In [10]:
flights["time_hour"]

0        2013-01-01 10:00:00
1        2013-01-01 10:00:00
2        2013-01-01 10:00:00
3        2013-01-01 10:00:00
4        2013-01-01 11:00:00
                 ...
336771   2013-09-30 18:00:00
336772   2013-10-01 02:00:00
336773   2013-09-30 16:00:00
336774   2013-09-30 15:00:00
336775   2013-09-30 12:00:00
Name: time_hour, Length: 336776, dtype: datetime64[us]

In [11]:
(flights.query("dest == 'IAH'").groupby(["year", "month", "day"])[["arr_delay"]].mean())

                arr_delay
year month day
2013 1     1    17.850000
           2     7.000000
           3    18.315789
           4    -3.200000
           5    20.230769
...                   ...
     12    27    6.166667
           28    9.500000
           29   23.611111
           30   23.684211
           31   -4.933333

[365 rows x 1 columns]

In [12]:
(flights.query("dest == 'ORD'").groupby(["year", "month", "day"])[["arr_delay"]].mean())

                arr_delay
year month day
2013 1     1    12.170213
           2    10.795455
           3     7.113636
           4    -2.108696
           5     5.615385
...                   ...
     12    27  -11.026316
           28   -8.523810
           29   29.483871
           30    2.945946
           31    5.375000

[365 rows x 1 columns]

In [13]:
import numpy as np

df = pd.DataFrame(
    data=np.reshape(range(36), (6, 6)),
    index=["a", "b", "c", "d", "e", "f"],
    columns=["col" + str(i) for i in range(6)],
    dtype=float,
)
df["col6"] = ["apple", "orange", "pineapple", "mango", "kiwi", "lemon"]
df

   col0  col1  col2  col3  col4  col5       col6
a   0.0   1.0   2.0   3.0   4.0   5.0      apple
b   6.0   7.0   8.0   9.0  10.0  11.0     orange
c  12.0  13.0  14.0  15.0  16.0  17.0  pineapple
d  18.0  19.0  20.0  21.0  22.0  23.0      mango
e  24.0  25.0  26.0  27.0  28.0  29.0       kiwi
f  30.0  31.0  32.0  33.0  34.0  35.0      lemon

In [14]:
df.loc[["a", "b"]]

   col0  col1  col2  col3  col4  col5    col6
a   0.0   1.0   2.0   3.0   4.0   5.0   apple
b   6.0   7.0   8.0   9.0  10.0  11.0  orange

In [15]:
df.loc["a"]

col0      0.0
col1      1.0
col2      2.0
col3      3.0
col4      4.0
col5      5.0
col6    apple
Name: a, dtype: object

In [16]:
df.iloc[[0, 2]]

   col0  col1  col2  col3  col4  col5       col6
a   0.0   1.0   2.0   3.0   4.0   5.0      apple
c  12.0  13.0  14.0  15.0  16.0  17.0  pineapple

In [20]:
df.iloc[2:4]

   col0  col1  col2  col3  col4  col5       col6
c  12.0  13.0  14.0  15.0  16.0  17.0  pineapple
d  18.0  19.0  20.0  21.0  22.0  23.0      mango