From: https://aeturrell.github.io/python4DS/data-visualise.html

In [5]:
from lets_plot import *
from palmerpenguins import load_penguins

LetsPlot.setup_html()

In [6]:
penguins = load_penguins()
penguins

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007
...,...,...,...,...,...,...,...,...
339,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009
340,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009
341,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male,2009
342,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male,2009
343,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female,2009

In [7]:
penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007

In [8]:
(
    ggplot(penguins, aes(x="flipper_length_mm", y="body_mass_g"))
    + geom_point(aes(color="species", shape="species"))
    + geom_smooth(method="lm")
    + labs(
        title="Body mass and flipper length",
        subtitle="Dimensions for Adelie, Chinstrap, and Gentoo Penguins",
        x="Flipper length (mm)",
        y="Body mass (g)",
        color="Species",
        shape="Species",
    )
)

The first argument of `ggplot()` is the dataset to use in the graph and so `ggplot(data = penguins)` creates an empty graph that is primed to display the penguins data, but since we haven’t told it how to visualise it yet, for now it’s empty. Because it’s empty, running this alone would raise an error message: it’s an empty canvas that you’ll paint the remaining layers of your plot onto.

In [9]:
ggplot(data = penguins)

The `mapping` argument of the `ggplot()` function defines how variables in your dataset are mapped to visual properties (aesthetics) of your plot. The `mapping` argument is always defined in the `aes()` function, and the x and y arguments of `aes()` specify which variables to map to the x and y axes. For now, we will only map flipper length to the x aesthetic and body mass to the y aesthetic. letsplot looks for the mapped variables in the `data` argument, in this case, `penguins`.

In [10]:
ggplot(
  data = penguins,
  mapping = aes(x = "flipper_length_mm", y = "body_mass_g")
)

how to represent the observations from our data frame on our plot:

we need to define a geom: the geometrical object that a plot uses to represent data. These geometric objects are made available in letsplot with functions that start with geom_.

People often describe plots by the type of geom that the plot uses. For example, bar charts use bar geoms (geom_bar()), line charts use line geoms (geom_line()), boxplots use boxplot geoms (geom_boxplot()), scatterplots use point geoms (geom_point()), and so on.

The function geom_point() adds a layer of points to your plot, which creates a scatterplot. letsplot comes with many geom functions that each adds a different type of layer to a plot.

In [11]:
(
    ggplot(data=penguins, mapping=aes(x="flipper_length_mm", y="body_mass_g"))
    + geom_point()
)

Let’s incorporate species into our plot and see if this reveals any additional insights into the apparent relationship between these variables. We will do this by representing species with different colored points.

To achieve this, will we need to modify the aesthetic or the geom? If you guessed “in the aesthetic mapping, inside of aes()”, you’re already getting the hang of creating data visualisations with letsplot! And if not, don’t worry.

In [12]:
(
    ggplot(
        data=penguins,
        mapping=aes(x="flipper_length_mm", y="body_mass_g", color="species"),
    )
    + geom_point()
)

Now let’s add one more layer: a smooth curve displaying the relationship between body mass and flipper length.

Before you proceed, refer back to the code above, and think about how we can add this to our existing plot.

Since this is a new geometric object representing our data, we will add a new geom as a layer on top of our point geom: geom_smooth().

And we will specify that we want to draw the line of best fit based on a linear model with method = "lm".

In [13]:
(
    ggplot(
        data=penguins,
        mapping=aes(x="flipper_length_mm", y="body_mass_g", color="species"),
    )
    + geom_point()
    + geom_smooth(method="lm")
)

When aesthetic mappings are defined in ggplot(), at the global level, they’re passed down to each of the subsequent geom layers of the plot.

However, each geom function in letplot can also take a mapping argument, which allows for aesthetic mappings at the local level that are added to those inherited from the global level.

Since we want points to be colored based on species but don’t want the lines to be separated out for them, we should specify color = species for geom_point() only: therefore we take it out of the global aes() and just add it to geom_point().

In [14]:
(
    ggplot(data=penguins, mapping=aes(x="flipper_length_mm", y="body_mass_g"))
    + geom_point(mapping=aes(color="species"))
    + geom_smooth(method="lm")
)

 in addition to color, we can also map species to the shape aesthetic.

In [15]:
(
    ggplot(data=penguins, mapping=aes(x="flipper_length_mm", y="body_mass_g"))
    + geom_point(mapping=aes(color="species", shape="species"))
    + geom_smooth(method="lm")
)

Some of the arguments to labs() might be self explanatory: title adds a title and subtitle adds a subtitle to the plot. Other arguments match the aesthetic mappings, x is the x-axis label, y is the y-axis label, and color and shape define the label for the legend.

In [23]:
(
    ggplot(data=penguins, mapping=aes(x="flipper_length_mm", y="body_mass_g"))
    + geom_point(aes(color="species", shape="species"))
    + geom_smooth(method="lm")
    + labs(
        title="Body mass and flipper length",
        subtitle="Dimensions for Adelie, Chinstrap, and Gentoo Penguins",
        x="Flipper length (mm)",
        y="Body mass (g)",
        color="Species",
        shape="Species",
    )
)

## Exercises (https://aeturrell.github.io/python4DS/data-visualise.html#exercises)

1. How many rows are in penguins? How many columns?

In [16]:
penguins.info()

<class 'pandas.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    str
 1   island             344 non-null    str
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    str
 7   year               344 non-null    int64
dtypes: float64(4), int64(1), str(3)
memory usage: 27.6 KB

2. What does the bill_depth_mm variable in the penguins data frame describe? Read the help for load_penguins() to find out, eg run help(load_penguins).

In [17]:
help(load_penguins)

Help on function load_penguins in module palmerpenguins.penguins:

load_penguins(return_X_y: bool = False, drop_na: bool = False) -> Union[pandas.DataFrame, Tuple[pandas.DataFrame, pandas.Series]]
    Load and return the penguins dataset (classification).

    The Palmer penguins dataset is a dataset for data exploration & visualization, and can be used as an
    alternative to the Iris dataset.

    +-------------------+----------------------+
    | Classes           | 3                    |
    +-------------------+----------------------+
    | Samples per class | [152,168,124]        |
    +-------------------+----------------------+
    | Samples total     | 344                  |
    +-------------------+----------------------+
    | Dimensionality    | 8                    |
    +-------------------+----------------------+
    | Features          | real, integer,       |
    |                   | string, positive     |
    +-------------------+----------------------+

    Read more in the :ref:`https://github.com/allisonhorst/palmerpenguins>`.

    Parameters
    ----------
    return_X_y : bool, default=False
        If True, returns a ``(data, target)`` tuple instead of a dataframe object.
        See below for more information about the `data` and `target` object.
    drop_na: bool, default=False
        If True drop rows from dataset that contain missing values. Only available when `return_X_y = True`

    Returns
    -------
    data : :class:`pandas.core.frame.DataFrame`
        A dataframe of shape (344, 8) and has the following columns:

        +-------------------+--------------------------------------------------------------------------+
        | Column            | Description                                                              |
        +===================+==========================================================================+
        | species           | A string denoting penguin species (Adélie, Chinstrap and Gentoo)        |
        +-------------------+--------------------------------------------------------------------------+
        | island            | A string denoting island in Palmer Archipelago, Antarctica (Biscoe,     |
        |                   | Dream or Torgersen)                                                      |
        +-------------------+--------------------------------------------------------------------------+
        | bill_length_mm    | A number denoting bill length (millimeters)                              |
        +-------------------+--------------------------------------------------------------------------+
        | bill_depth_mm     | A number denoting bill depth (millimeters)                               |
        +-------------------+--------------------------------------------------------------------------+
        | flipper_length_mm | An integer denoting flipper length (millimeters)                         |
        +-------------------+--------------------------------------------------------------------------+
        | body_mass_g       | An integer denoting body mass (grams)                                    |
        +-------------------+--------------------------------------------------------------------------+
        | sex               | A string denoting penguin sex (female, male)                             |
        +-------------------+--------------------------------------------------------------------------+
        | year              | An integer denoting the study year (2007, 2008, or 2009)                |
        +-------------------+--------------------------------------------------------------------------+

    (data, target) : tuple if ``return_X_y`` is True
        A tuple containing:

        data: DataFrame of shape (344, 4)
            Contains the four size measurements: bill_length_mm, bill_depth_mm,
            flipper_length_mm, and body_mass_g.

        target: Series of shape (344,)
            The classification target (penguin species).

    Examples
    --------
    Let's say you are interested in the samples 10, 80, and 140, and want to
    know their class name.
    >>> from palmerpenguins.penguins import load_penguins
    >>> penguins = load_penguins()
    >>> list(penguins.iloc[[1, 160, 300],0])
    ['Adelie', 'Gentoo', 'Chinstrap']
    >>> dict(pd.value_counts(penguins.species))
    {'Adelie': 152, 'Gentoo': 124, 'Chinstrap': 68}

3. Make a scatterplot of bill_depth_mm vs. bill_length_mm. That is, make a scatterplot with bill_depth_mm on the y-axis and bill_length_mm on the x-axis. Describe the relationship between these two variables.

In [18]:
(
    ggplot(data=penguins, mapping=aes(x="bill_length_mm", y="bill_depth_mm"))
    + geom_point()
)

In [26]:
(
    ggplot(data=penguins, mapping=aes(x="bill_length_mm", y="bill_depth_mm", color="species", shape="species"))
    + geom_point()
    + geom_smooth(method="lm")
    + labs(
        title="Bill debth and bill length",
        subtitle="Dimensions for Adelie, Chinstrap, and Gentoo Penguins",
        x="Bill length (mm)",
        y="Bill depth (mm)",
        color="Species",
        shape="Species",
    )
)